### ISSUE TITLE
Code Documentation 

### ISSUE THREAD

**Issue by bensonarafat** [bensonarafat/super_tooltip#112]
I just need the code base documented. 
Thanks

**Comment by RotRot-pi** [comment]
Hello! 
I'd love to take on this good first issue. 
Could you please provide more details on the specific areas or aspects of the codebase that need documentation to meet the expected results? 
Thanks!

**Comment by bensonarafat** [comment]
Thanks @RotRot-pi for your help 
The whole codebase needs comments on them. I've not had enough time to complete it for long now. 
But we could work on it together

**Comment by RotRot-pi** [comment]
Thanks @bensonarafat for the details, 
I'd be happy to help with commenting the codebase. 
Working together sounds great! 
How would you like to divide the work, or is there a particular section you'd like me to start with?

**Comment by bensonarafat** [comment]
You know how the plugin works right? 
You can start from here @RotRot-pi 
lib/src/super_tooltip.dart 
Any property you don't understand and why its been used let me know, so I can explain

**Comment by RotRot-pi** [comment]
@bensonarafat Thanks for the direction! I’ll start with lib/src/super_tooltip.dart. 
If I come across any properties that I don’t fully understand, I’ll reach out to you for clarification.
