### ISSUE TITLE
Show tooltip using a key

### ISSUE THREAD

**Issue by tbarbette** [bensonarafat/super_tooltip#20]
Hi,

Is it possible to show the tooltip at a given location using a key?
Eg : 
```

FloatingActionButton(
    key: _navigation
    ...
```

And then do tooltip.show(_navigation) ? That would be very helpful :) Keeping the BuildContext is cumbersome in some cases.

**Comment by escamoteur** [comment]
Checkout the branch 'newVersion' and tell us what you think about this approach?

**Comment by tbarbette** [comment]
I looked at the branch but I don't see any difference in the readme doc? Where should I look at?
Thanks for this plugin by the way :) I'm sending PR and issues but it's working great already :)

**Comment by escamoteur** [comment]
Hi, yeah, sorry, we didn't have time yet to update the reamdme, I recomment to check out the example.
I will check your PR now, thanks
