### ISSUE TITLE
The bubble arrow gets wrong position on nested navigator.

### ISSUE THREAD

**Issue by hnvn** [bensonarafat/super_tooltip#29]
In case of using nested navigator, the tooltip bubble shape gets wrong position of its arrow. 

- With nested navigator:
<img width="1280" alt="Screen Shot 2021-06-30 at 14 50 34" src="https://user-images.githubusercontent.com/5468513/123923007-c8ba7100-d9b2-11eb-871c-1b0265c06553.png">

- Without nested navigator:
<img width="497" alt="Screen Shot 2021-06-30 at 14 51 03" src="https://user-images.githubusercontent.com/5468513/123923065-d8d25080-d9b2-11eb-9e03-c014828ff58b.png">

**Comment by hnvn** [comment]
As further investigation, I can temporarily get around this issue by using `rootOverlay`

```
Overlay.of(targetContext, rootOverlay: true)
```

One more thing, when I try to debug the issue, I see a strange behavior of the tooltip. As first rendering, it gets correct arrow position but immediately being rebuilt and end up with the wrong arrow like the above image.

**Comment by dw2kim** [comment]
We also have the same issue

**Comment by mrgnhnt96** [comment]
Hey! Thanks for the issue 👍

Could you please provide reproduction steps to debug this? And minimal sample code if possible?
