### ISSUE TITLE
Overlay.of(context) return nullable OverlayState, should not be accessed directly

### ISSUE THREAD

**Issue by UKOM** [bensonarafat/super_tooltip#62]
Thanks for your working, i have used super_tooltip of version 0.9.6, it really helps me. Now when i tried to use the newest version in my new project, there is compilation error.

super_tooltip package version: 2.0.4  
flutter version: 3.3.10

Compilation error:  
super_tooltip-2.0.4/lib/src/super_tooltip.dart:201:29: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.  
super_tooltip-2.0.4/lib/src/super_tooltip.dart:351:25: Error: Method 'insertAll' cannot be called on 'OverlayState?' because it is potentially null.

**Comment by bensonarafat** [comment]
Thanks for this.. I'll look into it.

**Comment by bensonarafat** [comment]
@UKOM 
Pls can u share your code, so I will able to help on this? 
Thanks

**Comment by UKOM** [comment]
> @UKOM Pls can u share your code, so I will able to help on this? Thanks

There is nothing special, you can just run the sample code in README.md, and before that, make sure your flutter version is 3.3.10. I have tried to replace `overlay.of(context)` with `overlay.of(context)?` in lib/src/super_tooltip.dart source file, it just works fine.

**Comment by bensonarafat** [comment]
thanks
