### ISSUE TITLE
moving the repo to bensonarafat 

### ISSUE THREAD

**Issue by escamoteur** [bensonarafat/super_tooltip#64]
Hi @bensonarafat I see you are really taking the maintaining seriously

what about I move the repository to your users account?

Cheers
Thomas

**Comment by bensonarafat** [comment]
@escamoteur 
wow. 
Thanks, that will be great.

**Comment by escamoteur** [comment]
Leave a note about the origin in the readme :-)

**Comment by bensonarafat** [comment]
> Leave a note about the origin in the readme :-)

Okay

**Comment by escamoteur** [comment]
👍

**Comment by bensonarafat** [comment]
> Leave a note about the origin in the readme :-)

this is done.
