### ISSUE TITLE
Feature request: tap tooltip to dismiss

### ISSUE THREAD

**Issue by ingridwang** [bensonarafat/super_tooltip#68]
Super tooltip has been great so far - thank you! One thing we've noticed is that users sometimes expect to be able to dismiss the tooltip by tapping the tooltip itself, not the barrier.

Could this be added as an option? Happy to help implement as well.

**Comment by bensonarafat** [comment]
Great, 
Contribution is welcome. i preview ur PR and merge 
@ingridwang

**Comment by ingridwang** [comment]
Hey @bensonarafat, could you create a new release with these changes? Thank you!

**Comment by bensonarafat** [comment]
@ingridwang 
Thanks for the reminder, i'll do that shortly
