### ISSUE TITLE
Prevent user from dismissing when tapping outside while showBarrier is true

### ISSUE THREAD

**Issue by AnwarTuha** [bensonarafat/super_tooltip#87]
Hey there, this is a really useful package, and it has helped me a lot.
Can we prevent the dismissal of the tool tip when tapping outside while the showBarrier property is true?

**Comment by Jaydip6** [comment]
does anyone give me the answer...

how do we prevent the the dismissal of the tool tip when tapping outside on the screen in flutter app.

Please, reply ASAP.

**Comment by AlabasterAxe** [comment]
I have a PR to add this functionality here: https://github.com/bensonarafat/super_tooltip/pull/99

**Comment by bensonarafat** [comment]
Thank you @AlabasterAxe 
I'll look at it now.
