### ISSUE TITLE
[bug] Tooltip is shown by tap on child, can't disable, prevents child interaction

### ISSUE THREAD

**Issue by slavamarchenko** [bensonarafat/super_tooltip#89]
Ckicking on child just gives Tooltip shown
Caused by this code:
![image](https://github.com/bensonarafat/super_tooltip/assets/89074059/71ce577d-a3b4-455c-a6c8-921553b6c2fe)

It would be great to have a param for disabling this behaviour and maybe set GestureDetector mode to translucent.

**Comment by bensonarafat** [comment]
@slavamarchenko 
I dont see the need for this. 
Closing this. 
If there is a better reason why this should be added. I will look at it again. 
Thanks

**Comment by kashlo** [comment]
I have the same problem. Clicking on child of the tooltip shows the tooltip. 
How can I prevent showing tooltip on child click?

**Comment by danieeelfc** [comment]
> I have the same problem. Clicking on child of the tooltip shows the tooltip. How can I prevent showing tooltip on child click?

I'm also looking for this behaviour
