### ISSUE TITLE
any way to make the child passed in respond to touch/clicks?

### ISSUE THREAD

**Issue by righteoustales** [bensonarafat/super_tooltip#93]
I'm trying out super_tooltip. Very cool!

I noticed the area just above my tooltip does not respond to touch/click (see image below).

<img width="329" alt="Screenshot 2024-03-10 at 4 48 12 PM" src="https://github.com/bensonarafat/super_tooltip/assets/135474727/92b05c63-4331-4201-9e02-39d4cd85aa63">

I was trying to allow the user to click on the child passed in (the calculator icon in my example above) and react to that by calling onHide() on the controller. But the arrow seems to get in the way of the touch/click for the entire bottom half of the child it is on top of.  

Is there a way to make this area (the child) respond to touch/click? I tried increasing the arrowTipDistance. This makes the arrow appear not to overlay the child, but it also makes the unclickable area larger and the same issue still exists.

This is how I configured it.

      SuperTooltip(
        controller: toolTipController,
        content: styledMsg,
        arrowTipDistance: 0.0,
        hideTooltipOnTap: true,
        touchThroughAreaShape: ClipAreaShape.rectangle,
        minimumOutsideMargin: 0.0,
        showCloseButton: ShowCloseButton.none,
        showBarrier: true,
        fadeInDuration: const Duration(milliseconds: 500),
        barrierColor: const Color.fromARGB(50, 236, 216, 250),
        onHide: () {
          debugPrint("Tooltip onHide called");
          setState(() {});
        },
        onShow: () {
          debugPrint("Tooltip shown");
        },
        child: 
          child);

**Comment by righteoustales** [comment]
Btw, I only added the "Let's Go" button because I was unable to click on the (entire) child passed in.

**Comment by bensonarafat** [comment]
@righteoustales 

If you want to hide the tooltip when the Let's Go button is clicked 
You just have to pass the called the hideTooltip method like so ` await _controller.hideTooltip();`
